# Site settings
title: iOS URL Schemes
tagline:
copyright:
keywords:

description: iOS URL schemes is an awesome way to automate some parts of your live with you iOS device.

# Company info
author: M van Eijgen
email: contact@studioalloy.nl
website: //studioalloy.nl
github_username: mvaneijgen
twitter_username: mvaneijgen

# the base hostname & protocol for your site
url: ""
baseurl: "//mvaneijgen.nl/iOS-URL-Schemes/"

default_image: /image.jpg

# Collections
collections:
  scheme:
    output: false

# Pre-processing

markdown: kramdown
highlighter: pygments
safe: true
permalink: /blog/:title/ # YYYY/MM/DD/page-title/index.html
lsi: true # Lexical analysis (true) takes longer for higher quality
# sass:
#  style: :compressed

# Exclude from Jekyll processing

exclude: ["vendor", "README.md", "node_modules", "gulpfile.js", "package.json"]
